version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: PersonRegistryManager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  spring-boot-app:
    build:
      context: ./java-backend
      dockerfile: Dockerfile
    container_name: spring-boot-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  react-app:
    build:
      context: ./react-frontend
      dockerfile: Dockerfile
    container_name: react-app
    depends_on:
      - spring-boot-app
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://spring-boot-app:8080/api
