-- liquibase formatted sql

-- changeset Greg:1711971250259-1
CREATE TABLE "addresses" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 7) NOT NULL, "city" VARCHAR(255), "house_number" INTEGER NOT NULL, "street" VARCHAR(255), "zip_code" INTEGER NOT NULL, "person_id" BIGINT, CONSTRAINT "addresses_pkey" PRIMARY KEY ("id"));

-- changeset Greg:1711971250259-2
CREATE TABLE "persons" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 5) NOT NULL, "taj" INTEGER NOT NULL, "birthdate" VARCHAR(255), "birthplace" VARCHAR(255), "email" VARCHAR(255), "name" VARCHAR(255), "tax_id" INTEGER NOT NULL, CONSTRAINT "persons_pkey" PRIMARY KEY ("id"));

-- changeset Greg:1711971250259-3
CREATE TABLE "person_phone_numbers" ("person_id" BIGINT NOT NULL, "phone_numbers" VARCHAR(255));

-- changeset Greg:1711971250259-4
ALTER TABLE "addresses" ADD CONSTRAINT "fk41l4n7dtgs89q3500yfxolvyd" FOREIGN KEY ("person_id") REFERENCES "persons" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Greg:1711971250259-5
ALTER TABLE "person_phone_numbers" ADD CONSTRAINT "fk4fl3b8ukpjk4dmciln225wtle" FOREIGN KEY ("person_id") REFERENCES "persons" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Greg:person-data
INSERT INTO persons(name, taj, birthdate, birthplace, email, tax_id) VALUES ('Nagy Erik', 4537485, '2000-02-21', 'Budapest', 'nagy.erik@email.com', 7786443);
INSERT INTO persons(name, taj, birthdate, birthplace, email, tax_id) VALUES ('Kovács János', 3657485, '2000-02-21', 'Budapest', 'kovacs.janos@email.com', 7754342);
INSERT INTO persons(name, taj, birthdate, birthplace, email, tax_id) VALUES ('Kiss Lajos', 4678482, '2000-12-01', 'Budapest', 'kiss.lajos@email.com', 7312332);
INSERT INTO persons(name, taj, birthdate, birthplace, email, tax_id) VALUES ('Ferenc Anna', 4537655, '2000-03-11', 'Budapest', 'ferenc.anna@email.com', 7786441);

-- changeset Greg:address-data
INSERT INTO addresses(city, house_number, street, zip_code, person_id) VALUES ('Budapest', 5, 'Füge utca', 1010, (SELECT id FROM persons WHERE name = 'Nagy Erik'));
INSERT INTO addresses(city, house_number, street, zip_code, person_id) VALUES ('Budapest', 46, 'Szentendrei út', 1032, (SELECT id FROM persons WHERE name = 'Kovács János'));
INSERT INTO addresses(city, house_number, street, zip_code, person_id) VALUES ('Budapest', 13, 'Dézsa út', 1114, (SELECT id FROM persons WHERE name = 'Kiss Lajos'));
INSERT INTO addresses(city, house_number, street, zip_code, person_id) VALUES ('Budapest', 12, 'Alma utca', 1068, (SELECT id FROM persons WHERE name = 'Kiss Lajos'));
INSERT INTO addresses(city, house_number, street, zip_code, person_id) VALUES ('Budapest', 4, 'Körte utca', 1010, (SELECT id FROM persons WHERE name = 'Ferenc Anna'));

-- changeset Greg:phone-number-data
INSERT INTO person_phone_numbers(person_id, phone_numbers) VALUES ((SELECT id FROM persons WHERE name = 'Nagy Erik'), '06201234567');
INSERT INTO person_phone_numbers(person_id, phone_numbers) VALUES ((SELECT id FROM persons WHERE name = 'Kovács János'), '06301114568');
INSERT INTO person_phone_numbers(person_id, phone_numbers) VALUES ((SELECT id FROM persons WHERE name = 'Kiss Lajos'), '06301233255');
INSERT INTO person_phone_numbers(person_id, phone_numbers) VALUES ((SELECT id FROM persons WHERE name = 'Ferenc Anna'), '06701145363');