-- liquibase formatted sql

-- changeset Greg:1711971250259-1
CREATE TABLE "addresses" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 7) NOT NULL, "city" VARCHAR(255), "house_number" INTEGER NOT NULL, "street" VARCHAR(255), "zip_code" INTEGER NOT NULL, "person_id" BIGINT, CONSTRAINT "addresses_pkey" PRIMARY KEY ("id"));

-- changeset Greg:1711971250259-2
CREATE TABLE "persons" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 5) NOT NULL, "taj" INTEGER NOT NULL, "birthdate" VARCHAR(255), "birthplace" VARCHAR(255), "email" VARCHAR(255), "name" VARCHAR(255), "tax_id" INTEGER NOT NULL, CONSTRAINT "persons_pkey" PRIMARY KEY ("id"));

-- changeset Greg:1711971250259-3
CREATE TABLE "person_phone_numbers" ("person_id" BIGINT NOT NULL, "phone_numbers" VARCHAR(255));

-- changeset Greg:1711971250259-4
ALTER TABLE "addresses" ADD CONSTRAINT "fk41l4n7dtgs89q3500yfxolvyd" FOREIGN KEY ("person_id") REFERENCES "persons" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- changeset Greg:1711971250259-5
ALTER TABLE "person_phone_numbers" ADD CONSTRAINT "fk4fl3b8ukpjk4dmciln225wtle" FOREIGN KEY ("person_id") REFERENCES "persons" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

