spring:
  application:
    name: PersonRegistryManager
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://postgres:5432/PersonRegistryManager
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver