spring:
  application:
    name: PersonRegistryManager

  datasource:
    url: jdbc:postgresql://localhost:5432/PersonRegistryManager
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.sql
