spring.datasource.url= jdbc:sqlserver://localhost:5002;database=PersonRegistryManager;TrustServerCertificate=true;MultipleActiveResultSets=True;Persist Security Info=True;
spring.datasource.username=SA
spring.datasource.password=Asdf1234
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.SQLServerDialect
